import Header from "@/components/Header";
import LayoutClient from "./layout.client";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <LayoutClient>
          <Header />
          <main className="flex flex-col h-auto">{children}</main>
          <Footer />
        </LayoutClient>
      </body>
    </html>
  );
}
